# Generated by Django 4.0.3 on 2022-03-28 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_con', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='play_url',
        ),
        migrations.AddField(
            model_name='video',
            name='meeting_id',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='recording_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='video',
            name='recording_id',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='recording_start',
            field=models.DateTimeField(default='None'),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('recording_id', 'meeting_id')},
        ),
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
    ]
