# Generated by Django 4.0.3 on 2022-03-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid_con', '0002_rename_file_video_play_url_video_meeting_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
