# Generated by Django 4.0.3 on 2022-03-28 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vid_con', '0003_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_id', models.CharField(default='None', max_length=100)),
                ('meeting_id', models.CharField(default='None', max_length=100)),
                ('play_url', models.FileField(null=True, upload_to='zoom_media/', verbose_name='')),
                ('recording_start', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('recording_end', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'unique_together': {('recording_id', 'meeting_id')},
            },
        ),
    ]
