# Generated by Django 4.0.3 on 2022-03-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid_con', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='play_url',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
    ]
